export enum BotResponseCode {
  ADDED_HISTORY_EMPTY = 1,
  INVALID_INPUT = 2,
  LIST_HISTORY_SUCCESSFUL = 3,
  TRACK_ADDED_TO_PLAYLIST_FAILURE = 4,
  TRACK_ADDED_TO_PLAYLIST_SUCCESSFUL = 5,
  TRACK_ALREADY_ADDED_ON_PLAYLIST = 6,
  TRACK_NOT_FOUND = 7,
  TRACK_SAVE_TO_HISTORY_FAILURE = 8,
  TRACK_SAVE_TO_HISTORY_SUCCESSFUL = 9,
  TRACK_SEARCH_FAILURE = 10,
  INVALID_TRACK_ID = 10,
  TRACK_SEARCH_SUCCESSFUL = 11,
}
